---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: capstone-service-prod-blue
  namespace: capstone-prod-blue
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~1
spec:
  releaseName: capstone-service-prod-blue
  chart:
    git: git@github.com:florianseidel/DevOps_Capstone_Service
    path: src/helm/capstone-service
    ref: release/1.2.0
  values:
    image: florianseidel/capstone-service:1.2.0
    quarkus.profile: prod
    nodeSelector:
      role: prod-worker
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi