apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: capstone-ingress
  namespace: capstone-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /capstone(/|$)(.*)
            backend:
              serviceName: capstone-service-proxy
              servicePort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: capstone-service-proxy-blue
  namespace: capstone-ingress
spec:
  type: ExternalName
  #Change this for blue/green deployment switch
  externalName: capstone-service-prod-green.capstone-prod-green.svc.cluster.local
  ports:
    - port: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: capstone-service-proxy-blue
  namespace: capstone-ingress
spec:
  type: ExternalName
  #Change this for blue/green deployment switch
  externalName: capstone-service-prod-green.capstone-prod-green.svc.cluster.local
  ports:
    - port: 8080