apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    "63": AgBgDlbZPtfV98U+mZWKR7Z+7IaQCKP9oBQf/J34HUePfX9sJAtXcDINu9wtF7PNANcFMGPzzHYwVr4zbB2Hv9nT2DC2oFKaJAa57eahMuKeezY39KPhVqro9gNtQrklGGqb6bIM4BClKare9bPqpzISXfmj5NEefxLlKaGOX0Bs3WiS4kB/Ng5fCiMYNdNmwBd6vw9DxL/lNHFtPY0jCruwyqrd0HSzeJ9Y8jO8IrWikDXEfvV7z7tCQEuyXcpOLOXnIMRzTSVUUIYzgWC79SELuyTIMjXcuw6OfFc6nbqXLyVCOrS0W2/Zb7w/LjppZYI7fmeWBL3w8WdKXaFZS40WNLZ8HBFxpy9q2lmZheseT2+q/VYICszHLwkGeQ6zbo6ON4GhbbSY2noIEA+XU5I/3wdLzc8ZfcsQ26YU2I2fnuQRbZigWyTcuW8dJXjVJuhq1J4gguK2pmBa+MIyx+dmHWQnq5X5rn2zPKQStN1WYyRITZ80+WfS3W7WgJRXPN0Hj1SVfgtUMCjy+SZbdBv19UkptgqbA+Zo0kQUWaS/dlEjiFN3hfIQpUogBa+K61FcELy6H63lc0jQfOZbZCsHO3AOd4HLnUbSkWBwM2nwVxiDRnfdIIzvR18FJwsXvM5bhJTcJ9ReblE+dKSsIBbDZROb5ppAtanrp73VD0mwhjszC9mFkoIaG3GZRt2InA2Vu8bP0Pq3Ks0yEdafTw4WnfnxYnSk2D3hDl8rdjlgmXpUUGB1mmSt2NvuSopr4mPsyjLjFdK4Y4ywLsizZc/IW/A+cnyzhSZsyihSi/htl9hxdDAEHI78ag+26g==
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: default
status: {}

