apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    "63": AgCFuJE7C+vkvJCgxilHXCSDgt7fXmfwko7/nCS8qwbCvd1+Fa2f4qlGO4A+H1NJr+JGkS7XRmSugqHo8mc7x96VcLjwBWGfOGqNs0xj8OQ09THdGvt192quPcv2NEKa9LtK6Tb8SOQDfadhybHBdCUUN+g0cKU0gHyv7hMlCf6R0Tjr3ezAyRU+KL6orfU6RAIATu9tZqgecOFxMJRbOzBQREZooR4gLjtvwqYOKuHnHCZOo0FmTSLBLIo7QubG9Yy8hAGbaHmIsnaEzE2IuDdMjmlae8fxWCboHiHeli4wo1p/SH2Gwf//yaWzTRDll/7FVgeQAGUWnLRBrWSq9nB2LG07nEaaGZnKcSP2CI50oaFV82prOZVRvEtCSyvzXotehcTcZOJrli69XH+xRGxwu8GlxrFHbyQS8vjyStR0gcIcrY5LwiIy34N3OQ1Sg4YtFZp0Owpzi6FIe+RVtB6PU4rFVzfHHX9iHGRPQ+Y/lW1kjFFiPvBZd4GSho3Tso9oTubOYXVgCkems+dda4ESqnU+Fg3deH1OLJIYd/iMmTSPRjJ0fXIXJmhZiompoqEqW87EuLEanD+kL4edv7wL+SXzKkdVq8F4RxL6eJl7rowp8hSMlRYZJb4d2Ahd0JaNm/VtuamyoVsQANOezIcJcybr8sm5Jm05tpgUZKBLrBgOktEVBODMe8j9gCwnltbaPN5jKH2rbkfPuRqRncXlY7x/V0uXBbemfnn81h9Tgu6oU8Zf6iN7Y9l2S1S8diRU0BA7P368RwmgKnfYBzlDfb47uzhFpQtUvUPyZVYZpuxYieQlZqzgThQ4Pw==
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: default
status: {}

