apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: capstone-build
spec:
  encryptedData:
    "63": AgCs/Kmv8jIsmDvjgVyKf1sU7b3b6XOc9w3UV8ZSOu+lTdL29ukocdkVPxRLRgM08xYCCZg2dcRuDvh2qPXwH68jjlArubXLzRntLnnfsycalREyYzrb3ZT6So0sc5efAmfmfIe3pM/h8d131dTAuBM0YnsqkzKtVFdWpqT1UQTuGhsSGwDnc+K1FIq3Xc4wpE30/I26033ffUayjzEp2wZ4Iv7KPzaVs0megVUV0rglGdHOxQxL6EbvMT6PehPOhJQf/MnfoyIZ75TZKDDLPbloa+XDhWXM41tK3d1NnDCbSxgroED++IKK182QySWLlB4s4GiOjhAvqWMKrX/yk1XgWt0RJ1M6eXQCFGWpo7AoDZ9Of3H/vHCxSgG+QnhvpS+wCVazqiuCvWPJXd//Pr3ESsgtdI8NV1pxcTCRf20qkodSPAaT8VlTIaDO09jV4HonGBy9JmJ/P/rC12DiyZ2gG3iNkpwZDetp2jaAyjbAlaTTPFHUkZBAed+KUG3ROl9oxk9OTxJ+yWpBioJKBV81F/WI3Sq7bprlhBRnMTLKv0EqtWdgaoTVLLhqjfOQHpCly3zsg+DlMkcV2kDGM76ioCoEqSXaMsRMVDDnXpGz5PYXBGjksyXmvgQrtcALACNkdeT4P62AsY5KdXApXh37E7MJyrSn9gZrI8oR+ddJbMrw0eGr4CUldcwezdH7k0Sz6jvb5NF06OBhczyvMUD0P0ZlKPRwIEsZYeYxQQNXBgdR70qsjGlQ7xKHlcvYUequvMRpx87dGRxVGv9Uolx01reOotQWlPxdZ8XDn4iquzy6sGNDqm8pkgA=
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: capstone-build
status: {}

