apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    "63": AgBL5LE+zbiMO0ckylqR0tZqLDwk76dZ35/lyOIhtu9CcCRcxE03h6GB+gamUxRwgS5yvfJ50YX3VOayzPYe0KaSj6BTC9+AoMjiXvTpvYA7x+X1YWsUVsW+FQa1Kvh/Q7dttOCzLqnbhOw7tGQt7Sla9phcltQafsKdkXtnlVoMpuN7UEEFV479620N92trcqgjYpZLdEeTQcfKsoiygipsSRAF7M7hOcoZ3GdEL+vjcZeMR7lY+7fYiQgJmLFYF6OHDQxaksfr8sDORdz/fI7VHCScI6/+1UH4yoaDNppmiD5pgvd0XLn+rn4NoC8cXeSyHiKHwqSNUfQVfGmpqgLsOJKLA12afwFClMrNWcG29hKM0Wf6HaeMTH9AqZmUIo7PwJ/ZunEMkLCMcQJgABccJ+0wR4zUs7guaFIec4805ArtLQ5mvdCUhvQVPs2mxnyNxwTGmVHR/cYaJz7UWDdbp7kk1EpbXt+k55f0c5tDcNaSRKstYCpqU+EaAs0JIDjACaFiJic9faAQ++AWDppyCIkh10M/vkGe9/32w9XbtwittyIF60WoKDa/IGnOmRBBXHF6rYZeFrLkkihYH7Y29XcH95OhVvdrd7TgEoKmtmkxLgHPFNBq0X8anXh3wF1O+aeLctH45hmDzMv0jKlkpR5C6wOleZg257IfH3D2vrRJjh44SnS5pGSQhLKR2XMItCHqYURffLSJxFPRKt4JYnU1XMRgCeKaSR9nLEN8A+1TbRB5fn+qQOc8IyqIv1wQZnVm3wc5w9L6xJF8O3Ep6+jFwWoisiGmq5bDYkrLlFppfYCDDzXXY9SK4w==
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: default
status: {}

