apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    "63": AgA0fBANSF5z5MJv/hljYB98P3gdqDYjeeyAcE9GermE2R1wTzak9uC+QjeUoilq7tImYQfh+ABz5ce/8KESFhxqnLD9y5pqUWTrzARavfFM8cwRedh1NudlDwL8VTlUqmKBocZSgIqs9QmMng8EAU0j0zQt3EbYpXsV7Qc3HJaqT2JIL/aBAf0dptX+U+dcAFGs/70g86XQLPJKAx0ANnPitH7bLd3dqhuVP+TAqZ/wXqyw4gEgJM7h1TmeyDZKUb/FscyYFnx+vPcQ2cLgkOhFGHMOlb84Q/r3hEgi/RuJwGimZ/M//yVUlnMVv8dkrz+Gl2yeS8X+8CxUEnYcz3gYS989KetFQ3LBt57cTqFzUVezTIopDvuch9puezVADnxXbEbHMI1NlxqXNxoZJSg+fFAkt/SfJy6nSgiEp/s7FMk7hFjrGa1WBLWra7mjC8ezKYqyGNl15IAb9NqT31GLeG5hBph8Bg0dEURZ8rm4hUMIqUpwz323AInSC8WfOqdSgev66IfcrPw56DocgWJoczl5SILIvcCJ5wUhmswNzCsjYUNNaSByXY24EzghXnT/EdYo2KCzIgtu0wefX2Xp8ORF1AgMnR3WLfedRlfIqOIJbTKHR84/Yc758eYBWN0yyIVuPtqldnRnFJ3iROdF7Sn5T8gLeLCDS93LqTfh/v0F+hTi5gdVQq7qIEGkrfj2G+jqmfNM0s4EakkBVSYpca4BG3wON927pmhq1pUi5tFpMsEqs7CARhtNblYpAqW9k0G3WbNs+H31gYFU6ntaQdGrvv3kTJpfOm9/xbzRwUDLUkNHT3IXsSY=
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: default
status: {}

