apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    "63": AgBVIdKVbFZDqlLt5iYg7oLJwttQ7Xa9tTMKMbbvVwGagwl8TmlvwjQIH0Zxor77PYmINjFVlRirLBUOwdqd+kYjSWQQI45TPKuyVDprgHPZ042uThlW52bIqT8+WE15RdGYCFsEhKB5uSoqY6MYqAIg7akzTR4q/fGxC04R7IzAr7j9s2nn9ECd2UH7kCEM+zmOIUJXYYc5yRac/sKArJvxPHg+eJyDiUp/76j9wgm3tXl7SnLRFMsPXJYlZSS1pzk0wKP3V9kfyEmc+ExOC2T0W+VaFkQwTYU61ype11UMeJSm/fLHp8Ui1iyZahcbAY/bzkaCIE/wdMTkw8Qr/Uec+1OPraI4PrvK7Vr7Wwez4+dSYYSU9ZHUemzWPvTG7ce+b7aEuC6hgsFQ7lmJzk/gdrfHjzXesE7XlGYroOrkm4tm+gwhvfzFl+zNLqMEs/+zRugbv5UK4tD2d2WASt8b0utUwUHnfAvB76BjfdtsMQ5vug+NTItByOaGlPrG5cilqr9LKYwv4PZtwJdoj/AzGjTF/kEDBEYZE6yI9P83pkWWIbmOl515TmNTBWtNBdW6rFKheJO2Ehm7BuB0HXMSjVBTlcMVAqK9hk1Q0mvGnP1el2K6TPaj1WZu5jnUWrl//uWfigQpL9gY4WMWtSkyTl/TqSVC3rCwadRdVbm5I/w15g8eW+/4+K7EiUp+rqFHvWMOKJ2xLdzoDabuXGJ+QVHcbOSRsdQW4vD9zLf71PEi1eXVWPuIXbrEg3e3wM04d54+HY3F3Lh+Qxg0Ufmp0yiDh40VVJQYd4yJi7rgwYp3fMN/mycEvrru+g==
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: default
status: {}

