apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    "63": AgASqjZjyHq5Ld4APn61ypa5A1/v+ck8IDmpVFMOFQ1B+59bSN/AhGNashgHxtg1TgBkoi8OPtZ5oR894FbKHypA4K6KXHU3rZTfGcwpdNlqueKgUWqNqzJV3LLCYdRVMqWuqEtyy1Y7FaZ1LS6bPJzucj0YR9DPifSrxJXw1Nf3Bn2CrSSMqcjWIESwmdSG/anLOyYMuw85K/V5cWxdSwlb+cUPs7T6c8KGIWGtY1kVhALxLQeqg0Qyt4JvOvbPc7B1aq6S0qSDBQwHEK1c9giGo/xaiDjOxa++20G3XXYTd9KKvsqNLaeTQS8s7ObLgiH4KxfWsW1Ae0qamkoEXom4Xn9PWQ69qjGvVIQbCCQo2QnN2j4K/nYDw3MJqTUO+OhjIGE8lAsjZiZAzVL4wba68EW9EFvcQVvB5RN9Ez9zIZSH86WGtvpeWkDVjNBIEuhcXLNJdIs362yml+BUaw06tbErGWowvJ/G3nX1gjjcvsddxUqb93Ih732gEdFsbnKk2ImDjjkXS2SkGCJmviJiJb6eI/ULoqJbRt8PcDqcVDKrkPVHvusK9Hb2aAfTgu+Q2K0VNUXf92AylXFywLuVKGNqckrLMzKRBeHjPAFtYNvRcp+yafZPaKT4MpV2ubXFAazaAxY1rwBSwJI7XI9ag0EeLXuI1S39R4TzxgLj7oyvUowDFs3dwNYX3uWZZICexFnmsDsSPPikeZga/innLetCYrcWYJanEN0a0hTW+C5pqF3SS1swjGMATbyzKkqJDXfjePwPyeaVvyZZDA4XuXhE9zTxV4YjJ4mTwVdQrcQQ5wE/KUfWJ1E=
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: default
status: {}

