apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    "63": AgAOFqj2/O7tF1dPSGkA4V18VKpdJsH/08A2MRRO/+ZYY+JhS4hSCrim1I58lsstvkI8E35bJV2x4PvqSMkjzsMKc9iTc8eDC62RPKfF8vzd30E8/yk2AIE2ttc/brR1+y/0TiVqgx/PLtwh7boG9MHyY65oltvH1Lz64p/QYeB0ptegMTWQSdHqc0H/WEd9+Le4vNb6CLWDiFtPXWI6hyIslALQoUBSU9cG4u2JCe+54KXznvbb+tnI/PagkIp5lTW9SUtHAsKT1s1S4ETRLph+dP1OEqszzIs+SiW4tsPeEnIY941iVximjnScUSEl75mAlKFcwe0PkJ37d1BkUf06+YuAouE+JNUpoGTeXgovVen8hQNoxrFS+0YAyxCTHcbG8tLjcXJ137MiqNDlY1ne2Lo8rsNy7su005DQtN4XRv0rNLKnCQvnQESjw1qIlY8mZL3KCN6tabfHztUIq0eVO1WIQI/RaiegPzMei/68QPfAQETmDMM8vKM0UFzTlZiqfjX0AkfA8/7Gw+ykDt1w5mY9pfklb9coQLXajtviF+N6L+gpRP5WtQBburBoJMEyL/Axlhu1Ugw99Q/3/JXKqgTeZaOSykMYjZMMeL9djCI6o4rDic4Clfy6lNt6zWTSDu8y5UStU56t51kbax57WO9hUETfubFMCsR1LvbtSnIFodaY65ZQ87kXro5Ww0LBCm6ePBZv+9GCQ+VPDSfygMUD8snJziCGCJhm/WoNWNeZHdnmDMvknk/WkWbJ0IsfF1z4VAYzJaCjVLJBwsO5xhC4Kq0Wu+4/Tx3/6Keq6F1XU07PfjxNQ3xwSQ==
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: default
status: {}

