apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    "63": AgCZuCSWgeaM+13LU2T70uG62j4ekrlqzVwVp56DOAeE6i6fraIz+CEY2fhrLEmpWZwNmMtAdEMfML34GDHCVsABkjGARy141apuKY+Q8oXnqQ5mrpUVqg/+eScCE55oGfq2jhvJV1wRZs1uhlpYDi2Frhh0Dcpm6qI3afYLMhlAhux8mSr9B2FCnHNqoHkcQ5++7TP8DfgTIN3VUmzToxpOu3w1mqJNGQryMmbGcsfqwvPO1By5NIeJ371glopJj3PdCYoaE51/yNuBfnt3nPt5NiSOJ2YdEGGKE6LiXW9DjnO2xkiKSnvx1JJrtk6rxMIKGz6ql3uyDUYXUf9HMENMCouQnpDE+56dtjPlGhHkbL23WDXDjq5GtEh3YYUlxtlV9/VKMr9F4FnKSAu2zKHZfxs7N1SQ+jQHDq5URyI95+IKGjobv8W5RTgmMUyB4Czk1l/g7y8m7bbVoy1JEn0GzjWpIsB47Qj77L4dU/GmldbfqsWkuoGeA+o8ywEaC1uYhEpiroONOgVdOKdfq2l8fC6my1lpartFFOlQj1L38qZcMszeyh/uI3L8AlJsovhFNzrnAXGbybEs38w9JEL+FRcdvvOHyLeYszkirAsAN+IDFdBPTjB8617tYXJHJbnYU4Oc/xSoJbMK528oI5qE/ptVpblMSqHyB3EEE23BjBxIAZtPocvhTiZvizUmP0YcASbqpq3gcsL0AfFx310dnihEcnDg3VoOObrkfEltSkVtmi3zsi3DFOYpAmb67lHud+DrK+CZxiFUAtYOfvX8k/RrBcsx023PnofIiOIBWeLsUsLFTSmf5LMSXg==
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: default
status: {}

