apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    "63": AgBtw9iFBVulzZ3rdErf8l14NE8NiJvmWdESYq53h6VJaeJwnuh/INK09rYonuDw/9uimPPf3DakEJsGXvjp/t0RcRVg4Me0zeuuCorPoudCFxGlM/dUow6mqUrgBD9S11044n7NCsSnipVYk3/IZTJJxibLwNb4Xyrj346G1OoqY4Ah2PZEqoERvn6mkDhVkcl/R7C0yHNhm8PVfHNMJK7cI5yZmeVs5lxOJAkjOckr1e54z84oWjvVu8NK7olYmzWL6bP/van/Q2EKAqlXPk91pagqIheAhtCkGXGUbQJHbUkvIpD3YFq7uoCWJCayg6qcaWSrfSgbHhACkRLsUeXvya1oQ4o1ee6qCs8qzilLSp5QmcwsiK6ZglZnLQS7cQh9+9skESJugyp9Nm1fdPSIV3CQtKzjmYYg1uBOFWcKm7TdAebetqPjwQbFTkovcIBqVKzuXsy0wpzQxrfe3QTOUZMs2tjNoCEmv/3aFJpWCCX/8kvP9QSo22YK4lBuwAi0na6gYSX6HKR2ACcc5UNny15riZ6KgqAqDb1FjoYVsNIX2hbvT/3Uibg0934FkvrthOZLeOppdu2N5bLCq2p2WMpAyScRRR6GPJ1H1W8t8WxBaKcn+kJu70hsQ+6361vydvfwn2r/2ltXiPS6Mps8X+hQ4Et47lP/XFrynCxemTOa2f2P6cT8I864C+80GOea5K6V1yXDtMdRkajQNqez5DS1Ny/He11GM5ieBnJLUe3rsn2xJkBdv1faaN88TTHbGBY3Yu/Ugw3h3YkHFYrNV10DN1Aj+PXb0fOLs1OjT2eIdTUzrlDJxfo9yA==
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: default
status: {}

