kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: capstone-build
  name: builder-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]