apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: capstone-build
spec:
  encryptedData:
    .dockerconfigjson: AgAeG6o0KAWxTR86pNw6D8n/yX3kAYA6mg9BEIIwoT1PUaKOuwoD5e28/xI2N6lK7r8KxJCF0njn3HAyglLdHHli06tRMi7ewH9QKIuDENH/9Jb+8T5O2HY7yDbM+RnofvUjf9g4QYWm/8hNDnN9Ge1BEFO/BFuq11gIOcNfuS1Ff3yRGt0Rnwnow4huNb2Aqs/CKm0HKSvvL2Pd961EHriSvLbaTHyjbdiL6r9OvOuvP+0viZGhJG3axJwnCPgD749c6OJ1sEqFRupurwCDvPe6qToYExr6Rc9eImOMqiDThdMCRdLM9vabATwJjRhE2EfNabh3RnRgUo6pFCOpjd9S+zkBKmEg7Ffk18rRgbHrDuL6pQ8BzkvDIcV2F/Qf4xRHc2SDRWw5vzc36rsA9bGGLu8YceFOl2Q4ZSBnP9mYM83LPsm3IT7wVcxasyiMquEI5vRM0Q7jHsV4jjzlRiMSzKY2y/eBBI/QaxtLDvCgYjKjDiOur5B6MZJ7z5HKYmQX0kffitfQU/yPrRXIAU8tYo6o3VOeBjbIs0GOscCdRXW0Ffmw09BgJzEO8LDKimdLxYu+Q4j0q6CTNgpMEeCu9yCfMAGM7AjinVaSFK8ht1RJAd1bKtZWHt/GQkxWomvn+zkYCihr+VEi+hCCjIrvrnL9jWhzN9BKgacZCEiEYSbJFAYYXvdgHzYECPQMAJcj4vE2/S7phhB+Im8kHysAJxUFfnrt6y0qOgtJQGz4VAvxGgpzMjSVJELMmMpWK+vm502MOK8P8/0iRabcw7MmSJSY+2Nh9Fzm4jpv81c3ymsv4HZ03h/BvxhtwjSahJRmr5+ToL3XoWsIKKq9kJ3mhvub1vi10DmYdhOxqvZPJ57Q5ih28ULcq6e8Cw4=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: capstone-build
    type: kubernetes.io/dockerconfigjson
status: {}

