apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: capstone-build
spec:
  encryptedData:
    .dockerconfigjson: AgBtnKzZst/N3RHiPmp39bX792u/SLWk1utovRrHChYVaK2eB6o2h3gqXV1XeK+dCWuNoBNiqm1azGv6IzuL0IU8x6m1og0u8n5Wef0l40Qqhzl2iKnlyVmcSLjCWG0mXApVFDqxaz3797ARIbBWoh2Tlf4KqR39Oegg5OfYlQQnSi+mk6nO0oH/mwOBMhSvNtWUxEDXQxhmgo1f6SQKXOVmfH2v9HPGxa8jAHpz/Pg6HLNHcat8ecyLiHwEavE8hgOmaGl8hwjKQzBI2SU9+OjK54BjjQu0p6QtsHClHEAe+XPiFsd+CbXJoRX1LMsg3ZVhGr8Pv2ru4R3yGHbVmf72IiEWznKWoVi8Ju7RFs7yO84CAKOq/RjX3jj+FrJUh8KeFnYLBzw3B1i7dxCh7MPYk4KKmJV6HxssZj5OoQcROIecyLEvsXlzc3CKoFHBbX2Rw22BdFUgTXXFt8QmrcgswGCYQl0/mvG3jmLAbBnmyi5HnW23srVxT4CxPOlIvtXv8dujJdkhaLZGUz4y2M8CY95tb25RXFmfLqJCZlc7jtNyfvC2xao/EKI0Q9QiEr1VJhgn397KKCr0X/64YZvnrND0IzMXqrvIDX8fsNDA8DgijX5a1q+8Xf1TOcntzDrqAUKNAiFZO/8wWDUPwFodvIFuaREUcNN/9WZyvigen4GGPCm/XjR8LJqH76iHrr/joHWBYAWsieyIxKAt7eAACXFTr5Cz8mxCNZOR3LI4XZmwpRff4hZqo52Gvc4gxfWmjONkADn/FH1iS/u0d1PimbDegGfYQqeZqGqpunYnwe5YNJ2/LzX36O8GnmVL1jxsxJjRth0d4lJ57wf98XFSzkJm7Nu6ReoXGZSMYB9naz0bC93cKfS/a9/kyeag3BstlfAC4crv/IRC/ysjylOO+QYSj1ylkV/b9vjZosVR+LQ=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: capstone-build
    type: kubernetes.io/dockerconfigjson
status: {}

