---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: capstone-service-dev
  namespace: capstone-dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:master-*
spec:
  releaseName: capstone-service-dev
  chart:
    git: git@github.com:florianseidel/DevOps_Capstone_Service
    path: src/helm/capstone-service
    ref: master
  values:
    image: florianseidel/capstone-service:master-f59b4d8
    replicaCount: 1
    quarkus.profile: dev
    nodeSelector:
      role: worker
