apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: capstone-prod-green
spec:
  encryptedData:
    .dockerconfigjson: AgAduDy3NtPXmdCWlpjy5GHdmz6GyXjPOL8wW2lxWcau+6F0AgOwpbnYxo7Ll51oeBPFXApgmIshfEHQMojsxBrwACX81TZWqCsCBjxR7TkaJMt6d3e0ut/QZJv842sSpIzpwSko7lB92ibzcXlXl3SvZxnhc2LHNfX3GNTtFvcMidNmqD4vGjOQohLjFov7+N3E6d8mpb90bpskUnR/2X1yANs4v5EZ5OfwK6S/obGMZndRs81gvtbjODWu7blRS61ypP4cOaKahEmQMvsG533BTXfm649B9dGFi6mh/8IjxSx30nmoJdXfrbkesM7BlVLJW4M5HA8uvdUnxhuA/I0Cd3vWn7aqDwtkeDbOOG9EDTOCNwqrTmXH7i2aN8aJwFmwiIZOQpDNS6LlngZVp0XQnXoHnYIFh+G0k1L21h/uLqI2v2eX8Xl2zQtQO7VnZUX38xsWXbl4KgprS0dJuvK5KcK+i0WSXfKeG0UWJG3ZYQM9GE2iCwps6AeSJ5mik1BvQcn2VK0b2lfhv2LxftzyD3zfXqy8RbS1yvyXflNSm1Th4sPrPsBSU/OJ5U7NeSaLRHq83cWGoWGg+raPKiknezWES+wG1PhtQIA7itHDsAGEjX8gsElAaz3jsVyk4ul8lRDtWJ53tf6KjZvhUn7W+H8w5o6XiBllAJOfVZ9WqwMII5CnAjeYalZnTJInPUGCQMvUz/l/QhXaTyegWe8/GZl5mXbDY7ArQ7N5kGdD/oTfLUBCKEtXlsBWcdtCpO89b/9MJJE7wjL++WqG/E9Q0n4j0qQfbKFxx4i5dUAUjW5J59YsIJ743QuciFOO4so77yED1mqegXRyq+772hVG8chyHDcv0Mu1XiEUdlHpsdamHf5NtdlJhKx2zvk=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: capstone-prod-green
    type: kubernetes.io/dockerconfigjson
status: {}

