---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: capstone-service-stag
  namespace: capstone-stag
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.2
spec:
  releaseName: capstone-service-stag
  chart:
    git: git@github.com:florianseidel/DevOps_Capstone_Service
    path: src/helm/capstone-service
    ref: release/1.2.0
  values:
    image: florianseidel/capstone-service:1.2.0
    replicaCount: 1
    quarkus.profile: dev
    nodeSelector:
      role: worker
